package dao;
// Generated Apr 13, 2017 2:29:00 PM by Hibernate Tools 3.6.0



/**
 * HibernateDemo generated by hbm2java
 */
public class HibernateDemo  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String pswd;
     private String country;
     private String email;

    public HibernateDemo() {
    }

	
    public HibernateDemo(String firstName, String lastName, String pswd, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.pswd = pswd;
        this.email = email;
    }
    public HibernateDemo(String firstName, String lastName, String pswd, String country, String email) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.pswd = pswd;
       this.country = country;
       this.email = email;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPswd() {
        return this.pswd;
    }
    
    public void setPswd(String pswd) {
        this.pswd = pswd;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


